#!/bin/bash
# Buildwright Setup Script
# Run this in any project to add the autonomous development workflow
# Supports: Claude Code, OpenCode, OpenClaw, Cursor
#
# Canonical config lives in .buildwright/ (tool-agnostic)
# Sync script generates .claude/, .opencode/, and .cursor/rules/ from it

set -e

BASE_URL="https://raw.githubusercontent.com/raunakkathuria/buildwright/main"

echo "Setting up Buildwright Development Workflow..."

# ============================================================================
# Directory Structure — .buildwright/ is the canonical source
# ============================================================================
mkdir -p .buildwright/commands
mkdir -p .buildwright/steering
mkdir -p .buildwright/agents
mkdir -p .buildwright/claws
mkdir -p .buildwright/codebase
mkdir -p .buildwright/tasks
mkdir -p .claude           # For settings.json (Claude Code-specific)
mkdir -p docs/requirements
mkdir -p docs/specs
mkdir -p .github/workflows
mkdir -p scripts

echo "  Created directory structure"

# ============================================================================
# CLAUDE.md - Main agent instructions (references .buildwright/)
# ============================================================================
cat > CLAUDE.md << 'CLAUDE_EOF'
# Buildwright Development

## Mission
Agent-first autonomous development. Humans approve specs; agents implement, test, and ship.

## Steering Documents

At the start of every session, read **all** `.md` files in `.buildwright/steering/`.
Also read all `.md` files in `.buildwright/codebase/` if that directory exists — these
are codebase analysis docs (stack, architecture, conventions, concerns) generated by
/bw-analyse. Do not assume a fixed set of files; discover what is there.

## Agents & Claws
- Agent personas in `.buildwright/agents/` — Architect, Staff Engineer, Security Engineer
- Domain-specialist claws in `.buildwright/claws/` — Frontend, Backend, Database (+ TEMPLATE for custom)
- Use `/bw-claw` for cross-domain features that need the Claw Architecture

## Project Structure

`.buildwright/` is the canonical configuration directory (committed to git). Tool-specific directories are generated from it and gitignored:

```
.buildwright/           ← Canonical source (committed)
  agents/               ← Architect, Staff Engineer, Security Engineer
  claws/                ← Frontend, Backend, Database, TEMPLATE
  codebase/             ← Generated by /bw-analyse (stack, architecture, conventions, concerns)
  commands/             ← bw-new-feature, bw-claw, bw-quick, bw-ship, bw-verify, bw-help
  steering/             ← product.md, tech.md, quality-gates.md, naming-conventions.md
  tasks/

.claude/                ← Generated by `make sync` (gitignored, except settings.json)
.opencode/              ← Generated by `make sync` (gitignored)
.cursor/rules/          ← Generated by `make sync` (gitignored)
AGENTS.md               ← Generated by `make sync` (gitignored)
```

After cloning or editing `.buildwright/`, run `make sync` to regenerate tool-specific configs.

## Operating Mode

### Default Behavior
- AUTONOMOUS mode: Execute fully without asking for confirmation
- Verify your own work through tests and checks
- Commit when verification passes
- Only stop if genuinely blocked (missing info, failing tests after retries)
- **Autonomous failure handling**: When `BUILDWRIGHT_AUTO_APPROVE=true` (default) and any step fails after retries, commit completed work, push, create PR with failure details, and exit(1). In interactive mode (`BUILDWRIGHT_AUTO_APPROVE=false`), STOP and report blocker as before.

### Workflow Priority
1. **New features (single domain)**: /bw-new-feature → Research → Spec → Approval → Implement → Ship
2. **Cross-domain features**: /bw-claw → Architect decomposes → Claws execute per domain → Integrate → Ship
3. **Small tasks/bugs**: /bw-quick → Quick research → Implement → Verify → Commit
4. **Refactors**: /bw-new-feature (if scope unclear) or /bw-quick (if scope clear)
5. **Ship existing work**: /bw-ship → Verify → Security → Review → Push → PR
6. **Quick quality check**: /bw-verify → typecheck, lint, test, build
7. **Show commands**: /bw-help
8. **Analyse existing codebase**: /bw-analyse → reads codebase → writes structured docs to .buildwright/codebase/ → updates tech.md. Run first on any brownfield project.

## Command Discovery

Run once per session. Cache the result — do not re-detect on every step.

1. Read `.buildwright/steering/tech.md`. If "Project Commands" has real commands (not template placeholders) → use them. STOP.
2. Auto-detect from project files in priority order: `package.json` → Node.js (check lock files: `pnpm-lock.yaml`→pnpm, `yarn.lock`→yarn, `bun.lockb`→bun, else→npm) | `Cargo.toml` → cargo | `go.mod` → go | `pyproject.toml` → check `poetry.lock`→poetry, `uv.lock`→uv, else→pip/hatch | `setup.py` → pip | `requirements.txt` → pip | `Makefile` → read targets.
3. Derive four commands — typecheck, lint, test, build. If a stack has no equivalent for an operation, mark it SKIP (not a failure). Python has no build step; that's fine.
4. Write discovered commands to tech.md so future runs use step 1.
5. If still ambiguous: in a greenfield context go to the Greenfield Path (see bw-new-feature). Otherwise ask: "What commands run your tests, linter, and build?"

## Credentials & Environment Variables

| Variable | Default | Required | Purpose |
|----------|---------|----------|---------|
| `GITHUB_TOKEN` | — | Yes | Push branches and open PRs via `gh`. Needs `repo` scope. |
| `BUILDWRIGHT_AUTO_APPROVE` | `true` | No | Autonomous mode — skip human approval, fail gracefully on errors |
| `BUILDWRIGHT_AGENT_RETRIES` | `2` | No | Number of verify retries before giving up |

`GITHUB_TOKEN` is the only credential. Use a fine-grained personal access token scoped to a single repository with "Contents: Read and write" and "Pull requests: Read and write" permissions. `BUILDWRIGHT_AUTO_APPROVE` is a configuration flag, not a secret.

## Verification Loop (CRITICAL)

Before EVERY commit, discover commands first (see Command Discovery above), then run:

1. **Type check** — run DISCOVERED_TYPECHECK (SKIP gracefully if this stack has none)
2. **Lint** — run DISCOVERED_LINT (SKIP gracefully if this stack has none)
3. **Test** — run DISCOVERED_TEST
4. **Build** — run DISCOVERED_BUILD (SKIP gracefully if this stack has no build step, e.g. Python)

If ANY required step fails: fix and retry (max 2 attempts). If same error repeats or still failing: STOP and report blocker.

## Design Principles (ALWAYS APPLY)

1. **KISS (Keep It Simple, Stupid)**
   - Prefer simple solutions over clever ones
   - If it feels complex, step back and simplify
   - Code should be readable by a junior developer

2. **YAGNI (You Aren't Gonna Need It)**
   - Build only what's required NOW
   - No speculative features "for later"
   - Avoid abstractions until they're proven needed

3. **No Premature Optimization**
   - Make it work first, then make it fast (if needed)
   - Optimize only with profiling data
   - Readability > micro-optimizations

4. **Boring Technology**
   - Prefer proven, well-documented solutions
   - New tech only when it solves a real problem
   - Consider maintenance burden

5. **Fail Fast, Fail Loud**
   - Validate inputs at boundaries
   - Throw errors early with clear messages
   - No silent failures

## Code Standards
- Follow existing patterns in the codebase exactly
- Keep files under 500 lines; split proactively
- Write tests for all new functionality (TDD preferred)
- Avoid type system escape hatches (`any` in TypeScript, untyped `interface{}` in Go, `Any` in Python) — use proper types
- Use Decimal/BigDecimal for financial calculations, NEVER floating point
- All user inputs must be validated

## Git Rules
- Atomic commits: only commit files you changed
- Conventional commits: feat:, fix:, refactor:, test:, docs:, chore:
- List each file explicitly in commit message
- Never edit .env files
- Never run destructive git operations without explicit instruction
- Multi-agent safety: NEVER use git stash (other agents may be working)
- Only `.buildwright/` is committed — never commit `.claude/` or `.opencode/` content files
- After editing any file in `.buildwright/`, run `make sync` before committing

## Cross-Domain Features (Claw Architecture)
When a feature touches multiple domains (e.g., DB + API + UI):
1. `/bw-claw` triggers the Architect persona (`.buildwright/agents/architect.md`)
2. Architect registers new fields in `.buildwright/steering/naming-conventions.md` BEFORE spawning claws
3. Each claw (`.buildwright/claws/*.md`) executes its domain task using TDD
4. Claws derive naming from the conventions registry — they never invent their own
5. Architect integrates and runs quality gates

## Self-Improvement
When you discover a pattern, gotcha, or better approach:
- Add it below under "Learned Patterns"
- Keep entries concise (one line each)

## Learned Patterns
<!-- Agent adds entries here as it learns -->

CLAUDE_EOF

echo "  Created CLAUDE.md"

# ============================================================================
# .claude/settings.json - Claude Code permissions (stays in .claude/)
# ============================================================================
curl -sL "$BASE_URL/.claude/settings.json" > .claude/settings.json
echo "  Created .claude/settings.json"

# ============================================================================
# AGENTS — Download to .buildwright/ (canonical source)
# ============================================================================

curl -sL "$BASE_URL/.buildwright/agents/staff-engineer.md" > .buildwright/agents/staff-engineer.md
curl -sL "$BASE_URL/.buildwright/agents/security-engineer.md" > .buildwright/agents/security-engineer.md
curl -sL "$BASE_URL/.buildwright/agents/architect.md" > .buildwright/agents/architect.md
curl -sL "$BASE_URL/.buildwright/agents/README.md" > .buildwright/agents/README.md
echo "  Created agent personas (staff-engineer, security-engineer, architect)"

# ============================================================================
# CLAWS — Domain Specialist Templates
# ============================================================================

curl -sL "$BASE_URL/.buildwright/claws/README.md" > .buildwright/claws/README.md
curl -sL "$BASE_URL/.buildwright/claws/TEMPLATE.md" > .buildwright/claws/TEMPLATE.md
curl -sL "$BASE_URL/.buildwright/claws/frontend.md" > .buildwright/claws/frontend.md
curl -sL "$BASE_URL/.buildwright/claws/backend.md" > .buildwright/claws/backend.md
curl -sL "$BASE_URL/.buildwright/claws/database.md" > .buildwright/claws/database.md
curl -sL "$BASE_URL/.buildwright/claws/devops.md" > .buildwright/claws/devops.md
echo "  Created claw templates (frontend, backend, database, devops)"

# ============================================================================
# COMMANDS
# ============================================================================

curl -sL "$BASE_URL/.buildwright/commands/bw-new-feature.md" > .buildwright/commands/bw-new-feature.md
curl -sL "$BASE_URL/.buildwright/commands/bw-claw.md" > .buildwright/commands/bw-claw.md
curl -sL "$BASE_URL/.buildwright/commands/bw-quick.md" > .buildwright/commands/bw-quick.md
curl -sL "$BASE_URL/.buildwright/commands/bw-verify.md" > .buildwright/commands/bw-verify.md
curl -sL "$BASE_URL/.buildwright/commands/bw-ship.md" > .buildwright/commands/bw-ship.md
curl -sL "$BASE_URL/.buildwright/commands/bw-help.md" > .buildwright/commands/bw-help.md
curl -sL "$BASE_URL/.buildwright/commands/bw-analyse.md" > .buildwright/commands/bw-analyse.md
echo "  Created commands (bw-new-feature, bw-claw, bw-quick, bw-ship, bw-verify, bw-help, bw-analyse)"

# ============================================================================
# STEERING DOCUMENTS
# ============================================================================

curl -sL "$BASE_URL/.buildwright/steering/product.md" > .buildwright/steering/product.md
curl -sL "$BASE_URL/.buildwright/steering/tech.md" > .buildwright/steering/tech.md
curl -sL "$BASE_URL/.buildwright/steering/quality-gates.md" > .buildwright/steering/quality-gates.md
curl -sL "$BASE_URL/.buildwright/steering/naming-conventions.md" > .buildwright/steering/naming-conventions.md
echo "  Created steering documents (product, tech, quality-gates, naming-conventions)"

# ============================================================================
# TEMPLATES
# ============================================================================

curl -sL "$BASE_URL/docs/requirements/TEMPLATE.md" > docs/requirements/TEMPLATE.md
curl -sL "$BASE_URL/.buildwright/tasks/TEMPLATE.md" > .buildwright/tasks/TEMPLATE.md
echo "  Created templates"

# ============================================================================
# SCRIPTS
# ============================================================================

curl -sL "$BASE_URL/scripts/sync-agents.sh" > scripts/sync-agents.sh
curl -sL "$BASE_URL/scripts/validate-skill.sh" > scripts/validate-skill.sh
curl -sL "$BASE_URL/scripts/install-hooks.sh" > scripts/install-hooks.sh
mkdir -p scripts/hooks
curl -sL "$BASE_URL/scripts/hooks/pre-commit" > scripts/hooks/pre-commit
curl -sL "$BASE_URL/scripts/hooks/post-merge" > scripts/hooks/post-merge
curl -sL "$BASE_URL/scripts/hooks/post-checkout" > scripts/hooks/post-checkout
chmod +x scripts/sync-agents.sh scripts/validate-skill.sh scripts/install-hooks.sh \
         scripts/hooks/pre-commit scripts/hooks/post-merge scripts/hooks/post-checkout
echo "  Created scripts (sync-agents, validate-skill, install-hooks, hooks/)"

# ============================================================================
# MAKEFILE
# ============================================================================

curl -sL "$BASE_URL/Makefile" > Makefile

# ============================================================================
# SKILL.md
# ============================================================================

curl -sL "$BASE_URL/SKILL.md" > SKILL.md

# ============================================================================
# GITHUB WORKFLOW
# ============================================================================

curl -sL "$BASE_URL/.github/workflows/quality-gates.yml" > .github/workflows/quality-gates.yml
echo "  Created .github/workflows/quality-gates.yml"

# ============================================================================
# ENVIRONMENT VARIABLES
# ============================================================================

curl -sL "$BASE_URL/.env.example" > .env.example
echo "  Created .env.example"

# ============================================================================
# DOCUMENTATION
# ============================================================================

curl -sL "$BASE_URL/BUILDWRIGHT.md" > BUILDWRIGHT.md
echo "  Created BUILDWRIGHT.md"

# ============================================================================
# Sync: .buildwright/ → .claude/ + .opencode/ + .cursor/rules/ + AGENTS.md
# ============================================================================

scripts/sync-agents.sh
echo "  Synced tool-specific configs (.claude/, .opencode/, .cursor/rules/, AGENTS.md)"

# ============================================================================
# GIT HOOKS — auto-sync on .buildwright/ changes
# ============================================================================

git init
make install-hooks
echo "  Installed git hooks (pre-commit, post-merge, post-checkout)"

# ============================================================================
# COMPLETE
# ============================================================================

echo ""
echo "==============================================================="
echo "  SETUP COMPLETE"
echo "==============================================================="
echo ""
echo "  Canonical config:  .buildwright/   (edit this)"
echo "  Claude Code:       .claude/        (generated by sync)"
echo "  OpenCode:          .opencode/      (generated by sync)"
echo "  Cursor:            .cursor/rules/  (generated by sync)"
echo "  OpenClaw:          SKILL.md        (install via: make openclaw)"
echo ""
echo "  Next steps:"
echo "  1. Edit .buildwright/steering/product.md with your product context"
echo "  2. Edit .buildwright/steering/tech.md with your tech stack"
echo "  3. Optional: cp .env.example .env"
echo "  4. Start your agent tool and try:"
echo "     /bw-new-feature \"your feature description\""
echo "     /bw-claw \"cross-domain feature\""
echo "     /bw-quick \"fix the bug\""
echo ""
echo "  After editing .buildwright/, run: make sync  (or git hooks do it automatically)"
echo "==============================================================="
